### ISSUE TITLE
We experience issues when rolling on new patches 

### ISSUE THREAD

**Issue by madsnorgaard** [OS2Forms/os2forms_forloeb#33]
https://github.com/OS2Forms/os2forms_forloeb/blob/481d4acdc44467f00e7c56c2c9a9d1f6db2c7733/composer.json#L76

Does anyone have any suggestions as to why this and other patches fail during `composer install` ?

**Comment by andriyun** [comment]
Yeah... I've seen this too once or twice.
I didn't have time to read notice info. 
Can you add it into issue or steps how to reproduce it?
So it will be clear what is the bug

**Comment by madsnorgaard** [comment]
A fairly long error-log using the `fin composer patch:apply -vvv`
```

Loading from cache  - Installing drupal/config_entity_revisions (1.6.0): Reading /home/docker/.composer/cache/files/drupal/config_entity_revisions/bce7a6c1d6d0ba561a530cfaff56addbb8a79b5a.zip from cache
Loading from cache
 Extracting archiveExecuting command (CWD): unzip -qq  'web/modules/contrib/config_entity_revisions/16a68e5ca36d7f95c1c781a66bc7c11f.zip' -d '/var/www/vendor/composer/a698914b'
  - Applying patches for drupal/config_entity_revisions (1)
    ~ os2forms/os2forms_forloeb: https://www.drupal.org/files/issues/2019-04-15/config_entity_revisions-node_attach_error-3048218-2.patch [NEW]
      Error: Call to a member function id
      Executing command (web/modules/contrib/config_entity_revisions): which patch
      /usr/bin/patch
      (using cached result for: < which = 1)
      (using cached result for: which patch = 1)
      Executing command (web/modules/contrib/config_entity_revisions): /usr/bin/patch -t --verbose -p'0' --no-backup-if-mismatch --dry-run < '/var/www/vendor/vaimo/composer-patches/downloads/735594c8703f659dbbd6eb21868d2a47/config_entity_revisions-node_attach_error-3048218-2.patch'
      Hmm...  Looks like a unified diff to me...
      can't find file to patch at input line 5
      Perhaps you used the wrong -p or --strip option?
      The text leading up to this was:
      --------------------------
      |diff --git a/modules/webform_revisions/src/Entity/WebformRevisionsSubmission.php b/modules/webform_revisions/src/Entity/WebformRevisionsSubmission.php
      |index 04bfbfa..3f26913 100644
      |--- a/modules/webform_revisions/src/Entity/WebformRevisionsSubmission.php
      |+++ b/modules/webform_revisions/src/Entity/WebformRevisionsSubmission.php
      --------------------------
      No file to patch.  Skipping patch.
      Hunk #1 ignored at 66.
      1 out of 1 hunk ignored
      done
      CHECK (type=PATCH) failed with p=0
      (using cached result for: < which = 1)
      Executing command (web/modules/contrib/config_entity_revisions): which git
      /usr/bin/git
      *** The expected result to execution is a failure***
      Executing command (web/modules/contrib/config_entity_revisions): cd .. && /usr/bin/git rev-parse --is-inside-work-tree
      true
      PING (type=GIT) failed with p=0
      (using cached result for: < which = 1)
      (using cached result for: which patch = 1)
      Executing command (web/modules/contrib/config_entity_revisions): /usr/bin/patch -t --verbose -p'1' --no-backup-if-mismatch --dry-run < '/var/www/vendor/vaimo/composer-patches/downloads/735594c8703f659dbbd6eb21868d2a47/config_entity_revisions-node_attach_error-3048218-2.patch'
      Hmm...
      Looks like a unified diff to me...
      The text leading up to this was:
      --------------------------
      |diff --git a/modules/webform_revisions/src/Entity/WebformRevisionsSubmission.php b/modules/webform_revisions/src/Entity/WebformRevisionsSubmission.php
      |index 04bfbfa..3f26913 100644
      |--- a/modules/webform_revisions/src/Entity/WebformRevisionsSubmission.php
      |+++ b/modules/webform_revisions/src/Entity/WebformRevisionsSubmission.php
      --------------------------
      checking file modules/webform_revisions/src/Entity/WebformRevisionsSubmission.php
      Using Plan A...
      Hunk #1 FAILED at 66.
      1 out of 1 hunk FAILED
      done
      CHECK (type=PATCH) failed with p=1
      (using cached result for: < which = 1)
      (using cached result for: which git = 1)
      *** The expected result to execution is a failure***
      (using cached result for: cd .. && /usr/bin/git rev-parse --is-inside-work-tree = 1)
      PING (type=GIT) failed with p=1
      (using cached result for: < which = 1)
      (using cached result for: which patch = 1)
      Executing command (web/modules/contrib/config_entity_revisions): /usr/bin/patch -t --verbose -p'2' --no-backup-if-mismatch --dry-run < '/var/www/vendor/vaimo/composer-patches/downloads/735594c8703f659dbbd6eb21868d2a47/config_entity_revisions-node_attach_error-3048218-2.patch'
      Hmm...
      Looks like a unified diff to me...
      can't find file to patch at input line 5
      Perhaps you used the wrong -p or --strip option?
      The text leading up to this was:
      --------------------------
      |diff --git a/modules/webform_revisions/src/Entity/WebformRevisionsSubmission.php b/modules/webform_revisions/src/Entity/WebformRevisionsSubmission.php
      |index 04bfbfa..3f26913 100644
      |--- a/modules/webform_revisions/src/Entity/WebformRevisionsSubmission.php
      |+++ b/modules/webform_revisions/src/Entity/WebformRevisionsSubmission.php
      --------------------------
      No file to patch.  Skipping patch.
      Hunk #1 ignored at 66.
      1 out of 1 hunk ignored
      done
      CHECK (type=PATCH) failed with p=2
      (using cached result for: < which = 1)
      (using cached result for: which git = 1)
      *** The expected result to execution is a failure***
      (using cached result for: cd .. && /usr/bin/git rev-parse --is-inside-work-tree = 1)
      PING (type=GIT) failed with p=2
      Cannot apply patch /var/www/vendor/vaimo/composer-patches/downloads/735594c8703f659dbbd6eb21868d2a47/config_entity_revisions-node_attach_error-3048218-2.patch
      #0 /var/www/vendor/vaimo/composer-patches/src/Package/PatchApplier/ItemProcessor.php(69): Vaimo\ComposerPatches\Patch\File\Applier->applyFile('/var/www/vendor...', 'web/modules/con...', Array)
      #1 /var/www/vendor/vaimo/composer-patches/src/Package/PatchApplier.php(74): Vaimo\ComposerPatches\Package\PatchApplier\ItemProcessor->processFileInfo(Object(Composer\Package\CompletePackage), Array)
      #2 /var/www/vendor/vaimo/composer-patches/src/Repository/PatchesApplier.php(333): Vaimo\ComposerPatches\Package\PatchApplier->applyPatches(Object(Composer\Package\CompletePackage), Array)
      #3 /var/www/vendor/vaimo/composer-patches/src/Repository/PatchesApplier.php(290): Vaimo\ComposerPatches\Repository\PatchesApplier->processPatchesForPackage(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Package\CompletePackage), Array)
      #4 /var/www/vendor/vaimo/composer-patches/src/Repository/PatchesApplier.php(249): Vaimo\ComposerPatches\Repository\PatchesApplier->processQueues(Object(Composer\Package\CompletePackage), Object(Composer\Repository\InstalledFilesystemRepository), Array, Array)
      #5 /var/www/vendor/vaimo/composer-patches/src/Repository/PatchesApplier.php(225): Vaimo\ComposerPatches\Repository\PatchesApplier->updatePackage(Object(Composer\Package\CompletePackage), Object(Composer\Repository\InstalledFilesystemRepository), Array, Array)
      #6 /var/www/vendor/vaimo/composer-patches/src/Repository/Processor.php(45): Vaimo\ComposerPatches\Repository\PatchesApplier->apply(Object(Composer\Repository\InstalledFilesystemRepository), Array)
      #7 /var/www/vendor/vaimo/composer-patches/src/Bootstrap.php(123): Vaimo\ComposerPatches\Repository\Processor->process(Object(Composer\Repository\InstalledFilesystemRepository), Object(Vaimo\ComposerPatches\Patch\DefinitionList\Loader), Object(Vaimo\ComposerPatches\Repository\PatchesApplier))
      #8 /var/www/vendor/vaimo/composer-patches/src/Bootstrap.php(93): Vaimo\ComposerPatches\Bootstrap->applyPatchesWithConfig(Object(Vaimo\ComposerPatches\Config), true)
      #9 /var/www/vendor/vaimo/composer-patches/src/Composer/Commands/PatchCommand.php(167): Vaimo\ComposerPatches\Bootstrap->applyPatches(true)
      #10 /var/www/vendor/vaimo/composer-patches/src/Utils/RuntimeUtils.php(20): Vaimo\ComposerPatches\Composer\Commands\PatchCommand->Vaimo\ComposerPatches\Composer\Commands\{closure}()
      #11 /var/www/vendor/vaimo/composer-patches/src/Composer/Commands/PatchCommand.php(172): Vaimo\ComposerPatches\Utils\RuntimeUtils->executeWithPostAction(Object(Closure), Object(Closure))
      #12 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(245): Vaimo\ComposerPatches\Composer\Commands\PatchCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      #13 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      #14 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Vaimo\ComposerPatches\Composer\Commands\ApplyCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      #15 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(281): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      #16 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      #17 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(113): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      #18 phar:///usr/local/bin/composer/bin/composer(61): Composer\Console\Application->run()
      #19 /usr/local/bin/composer(24): require('phar:///usr/loc...')
      #20 {main}
      Failed to apply the patch. Halting execution!
      Probable causes for the failure:                                         
                                                                               
      > PATCH                                                                  
        @ b/modules/webform_revisions/src/Entity/WebformRevisionsSubmission.php
        ! Hunk #1 FAILED at 66.                                                
                                                                               
      (For full, unfiltered details please use: composer patch:apply -vvv)     
Reading ./composer.lock
Executing command (/var/www/web): git ls-files --error-unmatch '/var/www/web//autoload.php'
Executing command (/var/www): git rev-parse --show-toplevel
Executing command (/var/www): git check-ignore 'vendor'
> post-install-cmd: DrupalProject\composer\ScriptHandler::createRequiredFiles

```

I did however spot, that we are using the 1.6.0 version of the Config Entity Revision module, which could be the reason for this. I am going to update the module to 1.7.0 and test if the error is still present. Any other comments or feedback would be appreciated too.

**Comment by madsnorgaard** [comment]
This PR will remove the patch and install a newer version of the module: https://github.com/OS2Forms/os2forms_forloeb/pull/39

It does not address the reasons behind us having issues with adding new patches to os2forms_forloeb module.

**Comment by madsnorgaard** [comment]
Closing as issue is solved.
